/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/signUp'
import { Route as SignInRouteImport } from './routes/signIn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WallsNewRouteImport } from './routes/walls/new'
import { Route as WallIdViewRouteImport } from './routes/$wallId/view'
import { Route as WallIdSetRouteImport } from './routes/$wallId/set'
import { Route as WallIdHoldsRouteImport } from './routes/$wallId/holds'

const SignUpRoute = SignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallsNewRoute = WallsNewRouteImport.update({
  id: '/walls/new',
  path: '/walls/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WallIdViewRoute = WallIdViewRouteImport.update({
  id: '/$wallId/view',
  path: '/$wallId/view',
  getParentRoute: () => rootRouteImport,
} as any)
const WallIdSetRoute = WallIdSetRouteImport.update({
  id: '/$wallId/set',
  path: '/$wallId/set',
  getParentRoute: () => rootRouteImport,
} as any)
const WallIdHoldsRoute = WallIdHoldsRouteImport.update({
  id: '/$wallId/holds',
  path: '/$wallId/holds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/$wallId/holds': typeof WallIdHoldsRoute
  '/$wallId/set': typeof WallIdSetRoute
  '/$wallId/view': typeof WallIdViewRoute
  '/walls/new': typeof WallsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/$wallId/holds': typeof WallIdHoldsRoute
  '/$wallId/set': typeof WallIdSetRoute
  '/$wallId/view': typeof WallIdViewRoute
  '/walls/new': typeof WallsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/$wallId/holds': typeof WallIdHoldsRoute
  '/$wallId/set': typeof WallIdSetRoute
  '/$wallId/view': typeof WallIdViewRoute
  '/walls/new': typeof WallsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signIn'
    | '/signUp'
    | '/$wallId/holds'
    | '/$wallId/set'
    | '/$wallId/view'
    | '/walls/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signIn'
    | '/signUp'
    | '/$wallId/holds'
    | '/$wallId/set'
    | '/$wallId/view'
    | '/walls/new'
  id:
    | '__root__'
    | '/'
    | '/signIn'
    | '/signUp'
    | '/$wallId/holds'
    | '/$wallId/set'
    | '/$wallId/view'
    | '/walls/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  WallIdHoldsRoute: typeof WallIdHoldsRoute
  WallIdSetRoute: typeof WallIdSetRoute
  WallIdViewRoute: typeof WallIdViewRoute
  WallsNewRoute: typeof WallsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walls/new': {
      id: '/walls/new'
      path: '/walls/new'
      fullPath: '/walls/new'
      preLoaderRoute: typeof WallsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$wallId/view': {
      id: '/$wallId/view'
      path: '/$wallId/view'
      fullPath: '/$wallId/view'
      preLoaderRoute: typeof WallIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$wallId/set': {
      id: '/$wallId/set'
      path: '/$wallId/set'
      fullPath: '/$wallId/set'
      preLoaderRoute: typeof WallIdSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$wallId/holds': {
      id: '/$wallId/holds'
      path: '/$wallId/holds'
      fullPath: '/$wallId/holds'
      preLoaderRoute: typeof WallIdHoldsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  WallIdHoldsRoute: WallIdHoldsRoute,
  WallIdSetRoute: WallIdSetRoute,
  WallIdViewRoute: WallIdViewRoute,
  WallsNewRoute: WallsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
