/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/signUp'
import { Route as SignInRouteImport } from './routes/signIn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutsNewRouteImport } from './routes/layouts/new'
import { Route as LayoutIdViewRouteImport } from './routes/$layoutId/view'
import { Route as LayoutIdSetRouteImport } from './routes/$layoutId/set'
import { Route as LayoutIdHoldsRouteImport } from './routes/$layoutId/holds'

const SignUpRoute = SignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsNewRoute = LayoutsNewRouteImport.update({
  id: '/layouts/new',
  path: '/layouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIdViewRoute = LayoutIdViewRouteImport.update({
  id: '/$layoutId/view',
  path: '/$layoutId/view',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIdSetRoute = LayoutIdSetRouteImport.update({
  id: '/$layoutId/set',
  path: '/$layoutId/set',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIdHoldsRoute = LayoutIdHoldsRouteImport.update({
  id: '/$layoutId/holds',
  path: '/$layoutId/holds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/$layoutId/holds': typeof LayoutIdHoldsRoute
  '/$layoutId/set': typeof LayoutIdSetRoute
  '/$layoutId/view': typeof LayoutIdViewRoute
  '/layouts/new': typeof LayoutsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/$layoutId/holds': typeof LayoutIdHoldsRoute
  '/$layoutId/set': typeof LayoutIdSetRoute
  '/$layoutId/view': typeof LayoutIdViewRoute
  '/layouts/new': typeof LayoutsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/$layoutId/holds': typeof LayoutIdHoldsRoute
  '/$layoutId/set': typeof LayoutIdSetRoute
  '/$layoutId/view': typeof LayoutIdViewRoute
  '/layouts/new': typeof LayoutsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signIn'
    | '/signUp'
    | '/$layoutId/holds'
    | '/$layoutId/set'
    | '/$layoutId/view'
    | '/layouts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signIn'
    | '/signUp'
    | '/$layoutId/holds'
    | '/$layoutId/set'
    | '/$layoutId/view'
    | '/layouts/new'
  id:
    | '__root__'
    | '/'
    | '/signIn'
    | '/signUp'
    | '/$layoutId/holds'
    | '/$layoutId/set'
    | '/$layoutId/view'
    | '/layouts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  LayoutIdHoldsRoute: typeof LayoutIdHoldsRoute
  LayoutIdSetRoute: typeof LayoutIdSetRoute
  LayoutIdViewRoute: typeof LayoutIdViewRoute
  LayoutsNewRoute: typeof LayoutsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layouts/new': {
      id: '/layouts/new'
      path: '/layouts/new'
      fullPath: '/layouts/new'
      preLoaderRoute: typeof LayoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$layoutId/view': {
      id: '/$layoutId/view'
      path: '/$layoutId/view'
      fullPath: '/$layoutId/view'
      preLoaderRoute: typeof LayoutIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$layoutId/set': {
      id: '/$layoutId/set'
      path: '/$layoutId/set'
      fullPath: '/$layoutId/set'
      preLoaderRoute: typeof LayoutIdSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$layoutId/holds': {
      id: '/$layoutId/holds'
      path: '/$layoutId/holds'
      fullPath: '/$layoutId/holds'
      preLoaderRoute: typeof LayoutIdHoldsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  LayoutIdHoldsRoute: LayoutIdHoldsRoute,
  LayoutIdSetRoute: LayoutIdSetRoute,
  LayoutIdViewRoute: LayoutIdViewRoute,
  LayoutsNewRoute: LayoutsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
