import math
import torch
from torch import nn, Tensor
from torch.utils.data import TensorDataset, DataLoader
from pathlib import Path
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np

#-----------------------------------------------------------------------
# CONSTANTS
#-----------------------------------------------------------------------
DB_PATH = "data/storage.db"
SCALER_WEIGHTS_PATH = 'data/weights/scaler-weights.joblib'
DDPM_WEIGHTS_PATH = 'data/weights/ddpm-weights.pth'

GRADE_TO_DIFF = {
    "font": {
        "4a": 10, "4b": 11, "4c": 12,
        "5a": 13, "5b": 14, "5c": 15,
        "6a": 16, "6a+": 17, "6b": 18, "6b+": 19,
        "6c": 20, "6c+": 21,
        "7a": 22, "7a+": 23, "7b": 24, "7b+": 25,
        "7c": 26, "7c+": 27,
        "8a": 28, "8a+": 29, "8b": 30, "8b+": 31,
        "8c": 32, "8c+": 33,
    },
    "v_grade": {
        "V0-": 10, "V0": 11, "V0+": 12,
        "V1": 13, "V1+": 14, "V2": 15,
        "V3": 16, "V3+": 17, "V4": 18, "V4+": 19,
        "V5": 20, "V5+": 21, "V6": 22, "V6+": 22.5,
        "V7": 23, "V7+": 23.5, "V8": 24, "V8+": 25,
        "V9": 26, "V9+": 26.5, "V10": 27, "V10+": 27.5,
        "V11": 28, "V11+": 28.5, "V12": 29, "V12+": 29.5,
        "V13": 30, "V13+": 30.5, "V14": 31, "V14+": 31.5,
        "V15": 32, "V15+": 32.5, "V16": 33,
    },
}

#-----------------------------------------------------------------------
# UTILITY FUNCTIONS
#-----------------------------------------------------------------------

class SinusoidalPositionEmbeddings(nn.Module):
    """
    Standard sinusoidal positional embeddings for time steps.
    Helps the model understand 'where' it is in the diffusion process.
    """
    def __init__(self, dim: int = 128):
        super().__init__()
        self.dim = dim

    def forward(self, time):
        # time: (batch_size, 1)
        device = time.device
        half_dim = self.dim // 2
        embeddings = math.log(10000) / (half_dim - 1)
        embeddings = torch.exp(torch.arange(half_dim, device=device) * -embeddings)
        embeddings = time[:, 0].unsqueeze(1) * embeddings.unsqueeze(0)
        embeddings = torch.cat((embeddings.sin(), embeddings.cos()), dim=-1)
        return embeddings

def clear_compile_keys(filepath: Path | str, map_loc: str = "cpu")->dict:
    state_dict = torch.load(filepath, map_location=map_loc)
    new_state_dict = {}
    compile_prefix = "_orig_mod."
    for k, v in state_dict.items():
        if k.startswith(compile_prefix):
            new_k = k.replace(compile_prefix,"")
            new_state_dict[new_k] = v
        else:
            new_state_dict[k] = v
    return new_state_dict

def plot_climb(climb_data, title="Generated Climb"):
    """
    Visualizes a climb generated by a neural network.
    Args:
        climb_data (np.array): Shape [20, 4].
                               Features: [x, y, pull_x, pull_y]
        title (str): Title for the plot.
    """
    real_holds = climb_data[climb_data[:,0] > -1.1]
    x, y, pull_x, pull_y = real_holds.T
    is_hand = ((np.absolute(pull_y) > 0.2) | (np.absolute(pull_x) > 0.2))
    size = np.full((len(is_hand)),20) + np.full((len(is_hand)),30)*is_hand.astype(np.float32)
    fig, ax = plt.subplots(figsize=(6, 8))

    ax.scatter(x, y, c=is_hand, s=size)
    ax.quiver(x, y, pull_x*0.2, pull_y*0.2,
              color='green', alpha=0.6,
              angles='xy', scale_units='xy', scale=0.5,
              width=0.005, headwidth=3,
              label='Pull Direction', zorder=1)

    ax.set_title(title)
    ax.set_xlabel("X Position (Normalized)")
    ax.set_ylabel("Y Position (Normalized)")
    ax.set_ylim(-1,1)
    ax.set_xlim(-1,1)

    ax.set_aspect('equal')
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.legend(loc='upper right')


    plt.show()

def zero_com(climbs: Tensor, dim: int)->Tensor:
    """Perform Zero-Center-Of-Mass transformation on a batched input climbs Tensor of shape [B,S,dim+H], allowing the model being trained to be translation-invariant."""
    new = climbs.clone()
    com = new[:,:,:dim].mean(dim=1, keepdim=True)
    new[:,:,:dim] -= com
    return new

#Test single-batch memorization to ensure both model architectures are working properly.
def test_single_batch(
    model: nn.Module,
    dataset: TensorDataset,
    batch_size: int = 128,
    steps: int = 1000,
    lr = 1e-3,
    decay=0.0
):
    if decay == 0:
        optimizer = torch.optim.Adam(params=model.parameters(), lr=lr)
    else:
        optimizer = torch.optim.AdamW(params = model.parameters(), lr=lr, weight_decay=decay)

    loader = DataLoader(dataset=dataset, batch_size=batch_size)
    x, c = next(iter(loader))
    losses = []
    with tqdm(range(steps)) as pbar:
        for epoch in pbar:
            optimizer.zero_grad()
            loss = model.loss(x, c)
            loss.backward()
            grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            losses.append(loss.item())
            if epoch % 10 == 0:
                pbar.set_postfix_str(f"Loss: {loss.item():.4f}, Improvement:{losses[-1]-loss.item():.4f}, Grad Norm:{grad_norm:.4f}, Min loss:{min(losses) if len(losses) > 0 else 0:.5f}")
    print(f"Min loss:{min(losses):.5f}")
    return losses

def moving_average(values, window, gaussian = False):
    """
    Smooth values by doing a moving average
    :param values: (numpy array)
    :param window: (int)
    :return: (numpy array)
    """
    #We create the vector to multiply each value by to get the moving average. Essentially a vector of length n
    # in which each weight is 1/n.
    kernel = np.repeat(1.0, window) / window
    if (gaussian == True) :
        if window % 2 == 0:
            window+=1
        x = np.arange(-(window // 2), window // 2 + 1)
        kernel = np.exp(-(x ** 2) / (2 * window ** 2))
        kernel = kernel / np.sum(kernel)
    
    #The convolve function iteratively multiplies the first n values in the values array by the weights array.
    # with the given weights array, it essentially takes the moving average of each N values in the values array.
    return np.convolve(values, kernel, "valid")