/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WallsIndexRouteImport } from './routes/walls/index'
import { Route as WallsNewRouteImport } from './routes/walls/new'
import { Route as WallsWallIdIndexRouteImport } from './routes/walls/$wallId/index'
import { Route as WallsWallIdViewRouteImport } from './routes/walls/$wallId/view'
import { Route as WallsWallIdHoldsRouteImport } from './routes/walls/$wallId/holds'
import { Route as WallsWallIdGenerateRouteImport } from './routes/walls/$wallId/generate'
import { Route as WallsWallIdCreateRouteImport } from './routes/walls/$wallId/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallsIndexRoute = WallsIndexRouteImport.update({
  id: '/walls/',
  path: '/walls/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallsNewRoute = WallsNewRouteImport.update({
  id: '/walls/new',
  path: '/walls/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WallsWallIdIndexRoute = WallsWallIdIndexRouteImport.update({
  id: '/walls/$wallId/',
  path: '/walls/$wallId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallsWallIdViewRoute = WallsWallIdViewRouteImport.update({
  id: '/walls/$wallId/view',
  path: '/walls/$wallId/view',
  getParentRoute: () => rootRouteImport,
} as any)
const WallsWallIdHoldsRoute = WallsWallIdHoldsRouteImport.update({
  id: '/walls/$wallId/holds',
  path: '/walls/$wallId/holds',
  getParentRoute: () => rootRouteImport,
} as any)
const WallsWallIdGenerateRoute = WallsWallIdGenerateRouteImport.update({
  id: '/walls/$wallId/generate',
  path: '/walls/$wallId/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const WallsWallIdCreateRoute = WallsWallIdCreateRouteImport.update({
  id: '/walls/$wallId/create',
  path: '/walls/$wallId/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/walls/new': typeof WallsNewRoute
  '/walls': typeof WallsIndexRoute
  '/walls/$wallId/create': typeof WallsWallIdCreateRoute
  '/walls/$wallId/generate': typeof WallsWallIdGenerateRoute
  '/walls/$wallId/holds': typeof WallsWallIdHoldsRoute
  '/walls/$wallId/view': typeof WallsWallIdViewRoute
  '/walls/$wallId': typeof WallsWallIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/walls/new': typeof WallsNewRoute
  '/walls': typeof WallsIndexRoute
  '/walls/$wallId/create': typeof WallsWallIdCreateRoute
  '/walls/$wallId/generate': typeof WallsWallIdGenerateRoute
  '/walls/$wallId/holds': typeof WallsWallIdHoldsRoute
  '/walls/$wallId/view': typeof WallsWallIdViewRoute
  '/walls/$wallId': typeof WallsWallIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/walls/new': typeof WallsNewRoute
  '/walls/': typeof WallsIndexRoute
  '/walls/$wallId/create': typeof WallsWallIdCreateRoute
  '/walls/$wallId/generate': typeof WallsWallIdGenerateRoute
  '/walls/$wallId/holds': typeof WallsWallIdHoldsRoute
  '/walls/$wallId/view': typeof WallsWallIdViewRoute
  '/walls/$wallId/': typeof WallsWallIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/walls/new'
    | '/walls'
    | '/walls/$wallId/create'
    | '/walls/$wallId/generate'
    | '/walls/$wallId/holds'
    | '/walls/$wallId/view'
    | '/walls/$wallId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/walls/new'
    | '/walls'
    | '/walls/$wallId/create'
    | '/walls/$wallId/generate'
    | '/walls/$wallId/holds'
    | '/walls/$wallId/view'
    | '/walls/$wallId'
  id:
    | '__root__'
    | '/'
    | '/walls/new'
    | '/walls/'
    | '/walls/$wallId/create'
    | '/walls/$wallId/generate'
    | '/walls/$wallId/holds'
    | '/walls/$wallId/view'
    | '/walls/$wallId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WallsNewRoute: typeof WallsNewRoute
  WallsIndexRoute: typeof WallsIndexRoute
  WallsWallIdCreateRoute: typeof WallsWallIdCreateRoute
  WallsWallIdGenerateRoute: typeof WallsWallIdGenerateRoute
  WallsWallIdHoldsRoute: typeof WallsWallIdHoldsRoute
  WallsWallIdViewRoute: typeof WallsWallIdViewRoute
  WallsWallIdIndexRoute: typeof WallsWallIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walls/': {
      id: '/walls/'
      path: '/walls'
      fullPath: '/walls'
      preLoaderRoute: typeof WallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walls/new': {
      id: '/walls/new'
      path: '/walls/new'
      fullPath: '/walls/new'
      preLoaderRoute: typeof WallsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walls/$wallId/': {
      id: '/walls/$wallId/'
      path: '/walls/$wallId'
      fullPath: '/walls/$wallId'
      preLoaderRoute: typeof WallsWallIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walls/$wallId/view': {
      id: '/walls/$wallId/view'
      path: '/walls/$wallId/view'
      fullPath: '/walls/$wallId/view'
      preLoaderRoute: typeof WallsWallIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walls/$wallId/holds': {
      id: '/walls/$wallId/holds'
      path: '/walls/$wallId/holds'
      fullPath: '/walls/$wallId/holds'
      preLoaderRoute: typeof WallsWallIdHoldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walls/$wallId/generate': {
      id: '/walls/$wallId/generate'
      path: '/walls/$wallId/generate'
      fullPath: '/walls/$wallId/generate'
      preLoaderRoute: typeof WallsWallIdGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walls/$wallId/create': {
      id: '/walls/$wallId/create'
      path: '/walls/$wallId/create'
      fullPath: '/walls/$wallId/create'
      preLoaderRoute: typeof WallsWallIdCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WallsNewRoute: WallsNewRoute,
  WallsIndexRoute: WallsIndexRoute,
  WallsWallIdCreateRoute: WallsWallIdCreateRoute,
  WallsWallIdGenerateRoute: WallsWallIdGenerateRoute,
  WallsWallIdHoldsRoute: WallsWallIdHoldsRoute,
  WallsWallIdViewRoute: WallsWallIdViewRoute,
  WallsWallIdIndexRoute: WallsWallIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
